### ISSUE TITLE
Update CSS of this website

### ISSUE THREAD

**Issue by vaibhav-zemo** [vaibhav-zemo/Codeial#1]

**Comment by rakshitgondwal** [comment]
I would like to work on this issue.

**Comment by bhavyajshah** [comment]
Hello @vaibhav-zemo  Please provide a description so I can help you very easily. I would like to work on this issue.

**Comment by vaibhav-zemo** [comment]
@bhavyajshah you can work on this too and make pr

**Comment by adenugatani** [comment]
Hi, I would love to work on this, kindly assign to me

**Comment by vaibhav-zemo** [comment]
Ohk I am assigning to you.
@tanitoluwam

**Comment by adenugatani** [comment]
![Screenshot 2022-10-18 at 23 05 15](https://user-images.githubusercontent.com/91630659/196553747-4d25171f-6ee1-4ac8-adc0-e24074a7b24b.png)
i am having a hard time viewing the app in the browser, please help

**Comment by vaibhav-zemo** [comment]
You having error because you don't have redis server. To make any change you have to install Ubuntu and redis
